apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
        - image: idiordiev/online-shop-users-service
          imagePullPolicy: Always
          name: users-service
          ports:
            - containerPort: 8080
