apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-postgres
data:
  POSTGRES_USER: {{ .Values.postgres.secrets.username | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.secrets.password | b64enc | quote }}