apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-postgres
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.postgres.selector }}
  ports:
    - name: {{ .Values.postgres.port.name }}
      protocol: TCP
      port: {{ .Values.postgres.port.port }}
      targetPort: {{ .Values.postgres.port.containerPort }}
