apiVersion: v1
kind: Service
metadata:
  name: store-service-postgres
spec:
  type: ClusterIP
  selector:
    app: store-service-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432