apiVersion: apps/v1
kind: Deployment
metadata:
  name: basket-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basket-service
  template:
    metadata:
      labels:
        app: basket-service
    spec:
      containers:
        - image: idiordiev/online-shop-basket-service
          imagePullPolicy: Always
          name: basket-service
          ports:
            - containerPort: 80
