replicaCount: 1

selector: "orders-service"

container:
  name: "orders-service"
  image: "idiordiev/online-shop-orders-service"

service:
  ports:
    - name: http
      port: 80
      containerPort: 80

migrations:
  container:
    name: "run-migrations"
    image: "idiordiev/online-shop-orders-service-migrations"
    tag: "latest"
    
ingress:
  path: "/api/orders"
  port: "http"

postgres:
  replicaCount: 1
  selector: "orders-service-postgres"
  port:
    name: "default"
    port: 5432
    containerPort: 5432
  secrets:
    username: "postgres"
    password: "Ivanka123"
  configMap:
    database: "orders"
  container:
    name: "orders-service-postgres"
    image: "postgres"
    tag: "14.1-alpine3.15"
    volume:
      name: "orders-postgredb"
      mountPath: "/var/lib/orders-postgresql/data/"
    