replicaCount: 1

selector: "orders-service"

container:
  name: "orders-service"
  image: "idiordiev/online-shop-orders-service"

service:
  ports:
    - name: http
      port: 80
      containerPort: 80

migrations:
  container:
    name: "run-migrations"
    image: "idiordiev/online-shop-orders-service-migrations"
    tag: "latest"
    
ingress:
  path: "/api/orders"
  port: "http"

postgresql:
  fullnameOverride: "online-shop-orders-service-postgres"
  auth:
    postgresPassword: "Ivanka123"
    username: "postgres"
    password: "Ivanka123"
    database: "orders"
  primary:
    persistence: 
      size: 5Gi
      mountPath: "/var/lib/orders-postgresql/data/"
    