global:
  rabbitmq:
    host: "rabbitmq"
    port: 5672
    username: "test"
    password: "test_pass"
  postgresName: "postgres"
  postgresql: 
    service: 
      ports: 
        postgresql: 5432
    auth:
      postgresPassword: "DVypULxSCuElHPOUEobD"
      username: "onlineshop"
      password: "yhivJp9hroOoY70pASHC"

postgresql:
  nameOverride: "postgres"
  primary:
    persistence:
      size: 5Gi
      mountPath: "/var/lib/postgresql/data/"