replicaCount: 1

selector: "baskets-service"

container:
  name: "baskets-service"
  image: "idiordiev/online-shop-basket-service"

service:
  ports:
    - name: http
      port: 80
      containerPort: 80

migrations:
  container:
    name: "run-migrations"
    image: "idiordiev/online-shop-basket-service-migrations"
    tag: "latest"
    
ingress:
  path: "/api/baskets"
  port: "http"

postgresql:
  fullnameOverride: "online-shop-postgres"
  auth:
    username: "postgres"
    password: "DVypULxSCuElHPOUEobD"
    database: "baskets"
    