apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-service
  template:
    metadata:
      labels:
        app: store-service
    spec:
      containers:
        - name: store-service
          image: store-service
          imagePullPolicy: Never
          ports:
            - containerPort: 80
