apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-service
  template:
    metadata:
      labels:
        app: store-service
    spec:
      containers:
        - image: idiordiev/online-shop-store-service
          imagePullPolicy: Always
          name: store-service
          ports:
            - containerPort: 8080
